# Generated initial schema for Queen Tovah Foundation.
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("enquiry_type", models.CharField(choices=[("general", "General enquiry"), ("partnership", "Partnership"), ("humanitarian", "Humanitarian support"), ("scholarship", "Scholarship"), ("media", "Media")], default="general", max_length=20)),
                ("message", models.TextField()),
                ("status", models.CharField(choices=[("new", "New"), ("in-progress", "In progress"), ("closed", "Closed")], db_index=True, default="new", max_length=16)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "In review"), ("published", "Published")], db_index=True, default="draft", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("seo_keywords", models.CharField(blank=True, max_length=500)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("summary", models.TextField()),
                ("body", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["display_order", "title"]},
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "In review"), ("published", "Published")], db_index=True, default="draft", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("seo_keywords", models.CharField(blank=True, max_length=500)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=240, unique=True)),
                ("excerpt", models.TextField()),
                ("body", models.TextField(blank=True)),
                ("category", models.CharField(choices=[("humanitarian", "Humanitarian"), ("education", "Education"), ("youth-sports", "Youth & Sports"), ("community", "Community Development"), ("foundation", "Foundation"), ("partnership", "Partnership")], default="foundation", max_length=24)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("hero_image", models.ImageField(blank=True, null=True, upload_to="stories/%Y/%m/")),
                ("hero_alt", models.CharField(blank=True, max_length=220)),
                ("featured", models.BooleanField(default=False)),
                ("source_name", models.CharField(blank=True, max_length=180)),
                ("source_url", models.URLField(blank=True)),
            ],
            options={"ordering": ["-event_date", "-published_at", "-created_at"], "verbose_name_plural": "Stories"},
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "In review"), ("published", "Published")], db_index=True, default="draft", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("seo_keywords", models.CharField(blank=True, max_length=500)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("media_type", models.CharField(choices=[("image", "Image"), ("video", "Video")], default="image", max_length=12)),
                ("image", models.ImageField(blank=True, null=True, upload_to="gallery/%Y/%m/")),
                ("video_url", models.URLField(blank=True)),
                ("alt_text", models.CharField(blank=True, max_length=220)),
                ("caption", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["display_order", "-event_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="FounderProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "In review"), ("published", "Published")], db_index=True, default="draft", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("seo_keywords", models.CharField(blank=True, max_length=500)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="Founder", max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("primary_name", models.CharField(max_length=220)),
                ("public_record_name", models.CharField(blank=True, max_length=260)),
                ("maiden_name", models.CharField(blank=True, max_length=180)),
                ("headline", models.CharField(blank=True, max_length=260)),
                ("biography", models.TextField()),
                ("motto", models.CharField(blank=True, max_length=180)),
                ("faith_line", models.CharField(blank=True, max_length=180)),
                ("portrait", models.ImageField(blank=True, null=True, upload_to="founder/")),
                ("portrait_alt", models.CharField(blank=True, max_length=220)),
            ],
            options={"ordering": ["primary_name"]},
        ),
        migrations.CreateModel(
            name="FounderAchievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "In review"), ("published", "Published")], db_index=True, default="draft", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("seo_keywords", models.CharField(blank=True, max_length=500)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=240, unique=True)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("source_name", models.CharField(blank=True, max_length=180)),
                ("source_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["-year", "display_order", "title"]},
        ),
        migrations.CreateModel(
            name="ImpactMetric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "In review"), ("published", "Published")], db_index=True, default="draft", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("seo_keywords", models.CharField(blank=True, max_length=500)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("value", models.CharField(max_length=80)),
                ("unit", models.CharField(blank=True, max_length=80)),
                ("period", models.CharField(blank=True, max_length=120)),
                ("verification_note", models.TextField()),
                ("source_reference", models.CharField(blank=True, max_length=240)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["display_order", "title"]},
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "In review"), ("published", "Published")], db_index=True, default="draft", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("seo_keywords", models.CharField(blank=True, max_length=500)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=240, unique=True)),
                ("summary", models.TextField()),
                ("eligibility", models.TextField(blank=True)),
                ("application_status", models.CharField(choices=[("upcoming", "Upcoming"), ("open", "Open"), ("closed", "Closed")], default="upcoming", max_length=12)),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("application_url", models.URLField(blank=True)),
            ],
            options={"ordering": ["-opens_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "In review"), ("published", "Published")], db_index=True, default="draft", max_length=12)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("seo_keywords", models.CharField(blank=True, max_length=500)),
                ("og_image", models.ImageField(blank=True, null=True, upload_to="seo/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="partners/")),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["display_order", "title"]},
        ),
    ]
