# Generated by Django 5.2.18 on 2026-10-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scholarship_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Show this photo or video in the gallery on the selected program page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='core.program'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
